import { useRef, useCallback } from 'react'
import { motion } from 'motion/react'

interface SampleNotesProps {
  onSelect: (text: string) => void
  compact?: boolean
}

const samples: Record<string, string[]> = {
  '🧬 biology': [
    `Photosynthesis is the process by which green plants convert light energy into chemical energy. It occurs in the chloroplasts, specifically using chlorophyll. The process has two stages: light-dependent reactions (in thylakoid membranes) and the Calvin cycle (in the stroma). Water is split into oxygen and hydrogen. CO2 is fixed into glucose through carbon fixation. The overall equation: 6CO2 + 6H2O + light → C6H12O6 + 6O2. Factors affecting rate: light intensity, CO2 concentration, temperature. Photosystem I and II work together in the light reactions. ATP and NADPH are produced and used in the Calvin cycle.`,
    `Mitosis is the process of cell division that results in two genetically identical daughter cells. It consists of prophase, metaphase, anaphase, and telophase followed by cytokinesis. During prophase, chromatin condenses into chromosomes and the nuclear envelope breaks down. In metaphase, chromosomes align at the cell's equator. Anaphase separates sister chromatids to opposite poles. Telophase reforms nuclear envelopes around each set. Mitosis is essential for growth, repair, and asexual reproduction. The cell cycle includes interphase (G1, S, G2) where DNA replicates before mitosis begins.`,
    `DNA replication is semi-conservative — each new double helix contains one original and one new strand. Helicase unwinds the double helix at the replication fork. Primase adds RNA primers to start synthesis. DNA polymerase III adds nucleotides in the 5' to 3' direction. The leading strand is synthesized continuously; the lagging strand is made in Okazaki fragments. DNA ligase joins the fragments. Proofreading by polymerase reduces errors to about 1 in a billion. Telomerase extends telomeres in stem and germ cells to prevent chromosome shortening.`,
    `The immune system has two main branches: innate and adaptive immunity. Innate immunity provides immediate, non-specific defense through barriers (skin, mucous membranes), phagocytes (macrophages, neutrophils), and inflammation. Adaptive immunity is antigen-specific and develops memory. B cells produce antibodies (humoral immunity). T cells include helper T cells (CD4+) that coordinate responses and cytotoxic T cells (CD8+) that kill infected cells. Vaccines work by stimulating adaptive immunity without causing disease. Autoimmune disorders occur when the immune system attacks the body's own tissues.`,
    `Cellular respiration is the process by which cells break down glucose to produce ATP. It occurs in three stages: glycolysis (cytoplasm), the Krebs cycle (mitochondrial matrix), and the electron transport chain (inner mitochondrial membrane). Glycolysis splits glucose into two pyruvate molecules, producing 2 ATP and 2 NADH. The Krebs cycle generates CO2, NADH, FADH2, and 2 ATP per glucose. The electron transport chain uses NADH and FADH2 to create a proton gradient, driving ATP synthase to produce ~34 ATP. Total yield is approximately 36-38 ATP per glucose molecule. Anaerobic respiration (fermentation) produces only 2 ATP.`,
    `Genetics is the study of heredity and variation. Gregor Mendel established the laws of inheritance using pea plants. The law of segregation states that allele pairs separate during gamete formation. The law of independent assortment states that genes on different chromosomes sort independently. Dominant alleles mask recessive ones in heterozygotes. Punnett squares predict offspring ratios. Incomplete dominance produces blended phenotypes. Codominance expresses both alleles simultaneously (e.g., AB blood type). Polygenic traits are controlled by multiple genes. Linked genes on the same chromosome tend to be inherited together unless crossing over occurs.`,
    `Evolution by natural selection, proposed by Charles Darwin, explains how populations change over time. Individuals with traits better suited to their environment survive and reproduce more (fitness). Over generations, advantageous traits become more common. Evidence includes fossil records, comparative anatomy (homologous structures), embryology, molecular biology (DNA similarities), and biogeography. Speciation occurs when populations become reproductively isolated. Genetic drift affects small populations randomly. Gene flow introduces new alleles through migration. Hardy-Weinberg equilibrium describes a non-evolving population — deviations indicate evolution is occurring.`,
    `Ecology studies interactions between organisms and their environment. Ecosystems include biotic (living) and abiotic (non-living) components. Energy flows through trophic levels: producers, primary consumers, secondary consumers, and decomposers. Only about 10% of energy transfers between trophic levels. Biogeochemical cycles (carbon, nitrogen, water, phosphorus) recycle matter through ecosystems. Symbiotic relationships include mutualism (both benefit), commensalism (one benefits), and parasitism (one harmed). Biodiversity increases ecosystem stability. Keystone species have disproportionate effects on their ecosystems. Ecological succession describes how communities change over time after disturbance.`,
    `The nervous system coordinates body functions through electrical and chemical signals. Neurons are the basic units — they have dendrites (receive signals), a cell body, and an axon (transmits signals). Action potentials are all-or-nothing electrical impulses that travel along axons. Neurotransmitters cross synapses to transmit signals between neurons. The central nervous system (brain and spinal cord) processes information. The peripheral nervous system connects the CNS to the body. The autonomic nervous system controls involuntary functions — sympathetic (fight-or-flight) and parasympathetic (rest-and-digest). Reflex arcs bypass the brain for rapid responses.`,
    `Protein synthesis involves transcription and translation. In transcription, RNA polymerase reads DNA and creates mRNA in the nucleus. mRNA is processed (5' cap, poly-A tail, intron splicing) before leaving the nucleus. In translation, ribosomes read mRNA codons (triplets of nucleotides). tRNA molecules bring amino acids matching each codon via anticodons. The ribosome moves along mRNA, linking amino acids into a polypeptide chain. Start codon (AUG) initiates translation; stop codons (UAA, UAG, UGA) terminate it. Post-translational modifications fold and modify proteins into functional forms. Mutations in DNA can alter protein structure and function.`,
  ],
  '💻 computer science': [
    `A binary search tree (BST) is a data structure where each node has at most two children. The left subtree contains only nodes with keys less than the parent. The right subtree contains only nodes with keys greater than the parent. Search, insert, and delete operations have O(log n) average time complexity. In the worst case (unbalanced tree), operations degrade to O(n). Balanced BSTs like AVL trees and Red-Black trees maintain O(log n) guarantees. In-order traversal of a BST produces sorted output. BSTs are used in databases, file systems, and symbol tables.`,
    `TCP/IP is the foundational protocol suite of the internet. TCP (Transmission Control Protocol) provides reliable, ordered, error-checked delivery of data. It uses a three-way handshake (SYN, SYN-ACK, ACK) to establish connections. IP (Internet Protocol) handles addressing and routing packets across networks. IPv4 uses 32-bit addresses; IPv6 uses 128-bit addresses. UDP is a connectionless alternative to TCP — faster but unreliable. DNS translates domain names to IP addresses. HTTP operates on top of TCP at the application layer. Ports identify specific services (80 for HTTP, 443 for HTTPS).`,
    `Dynamic programming solves complex problems by breaking them into overlapping subproblems. It stores results of subproblems to avoid redundant computation (memoization or tabulation). Key properties: optimal substructure and overlapping subproblems. Classic examples include Fibonacci sequence, knapsack problem, longest common subsequence, and shortest path algorithms. Top-down approach uses recursion with memoization. Bottom-up approach fills a table iteratively. Time complexity often improves from exponential to polynomial. Bellman-Ford and Floyd-Warshall are DP-based graph algorithms.`,
    `Operating systems manage hardware resources and provide services to applications. The kernel is the core — it handles process scheduling, memory management, and I/O. Processes are isolated units of execution; threads share memory within a process. Virtual memory maps logical addresses to physical, enabling more memory than physically available. Page faults occur when accessed pages aren't in RAM. Scheduling algorithms include round-robin, priority-based, and multilevel feedback queues. Deadlocks happen when processes wait circularly for resources. Semaphores and mutexes prevent race conditions in concurrent programs.`,
    `Hash tables store key-value pairs using a hash function to compute an index into an array of buckets. Average-case O(1) for insert, delete, and lookup. Collisions occur when two keys hash to the same index. Resolution strategies: chaining (linked lists at each bucket) and open addressing (linear probing, quadratic probing, double hashing). Load factor = n/m (entries/buckets) — rehashing occurs when it exceeds a threshold (typically 0.75). Good hash functions distribute keys uniformly. Hash tables power dictionaries, caches, sets, and database indexing. Cryptographic hash functions (SHA-256) are one-way and collision-resistant.`,
    `Graph algorithms solve problems on networks of nodes and edges. BFS (breadth-first search) explores level by level — useful for shortest path in unweighted graphs. DFS (depth-first search) explores as deep as possible — useful for topological sorting, cycle detection, and connected components. Dijkstra's algorithm finds shortest paths with non-negative weights using a priority queue. Bellman-Ford handles negative weights. Kruskal's and Prim's algorithms find minimum spanning trees. A* search uses heuristics for pathfinding. Graph representations: adjacency matrix (O(V²) space) and adjacency list (O(V+E) space).`,
    `Machine learning enables computers to learn from data without explicit programming. Supervised learning trains on labeled data — classification (discrete output) and regression (continuous output). Common algorithms: linear regression, logistic regression, decision trees, random forests, SVMs, and neural networks. Unsupervised learning finds patterns in unlabeled data — clustering (K-means, DBSCAN) and dimensionality reduction (PCA). Overfitting occurs when a model memorizes training data; regularization (L1, L2) and cross-validation help prevent it. The bias-variance tradeoff balances underfitting and overfitting.`,
    `Relational databases organize data into tables with rows and columns. SQL (Structured Query Language) is used to query and manipulate data. Key operations: SELECT, INSERT, UPDATE, DELETE, JOIN. Primary keys uniquely identify rows. Foreign keys establish relationships between tables. Normalization (1NF, 2NF, 3NF) reduces data redundancy. ACID properties ensure transaction reliability: Atomicity, Consistency, Isolation, Durability. Indexes speed up queries but slow writes. B-trees and B+ trees are common index structures. NoSQL databases (document, key-value, graph, column-family) sacrifice some ACID guarantees for scalability and flexibility.`,
    `Sorting algorithms arrange elements in order. Bubble sort compares adjacent pairs — O(n²) but simple. Insertion sort builds the sorted array one element at a time — O(n²) but efficient for small or nearly sorted data. Merge sort divides and conquers — O(n log n) guaranteed, stable, but uses O(n) extra space. Quick sort picks a pivot and partitions — O(n log n) average, O(n²) worst case, in-place. Heap sort uses a binary heap — O(n log n) guaranteed, in-place. Counting sort and radix sort achieve O(n) for integers with bounded range. Stability means equal elements maintain their relative order.`,
    `Cryptography secures communication against adversaries. Symmetric encryption (AES, DES) uses one shared key for both encryption and decryption — fast but key distribution is challenging. Asymmetric encryption (RSA, ECC) uses a public-private key pair — slower but solves key distribution. Hash functions (SHA-256, MD5) produce fixed-size digests from arbitrary input — used for integrity verification. Digital signatures combine hashing with asymmetric keys for authentication. TLS/SSL secures web traffic using a handshake that combines asymmetric (key exchange) and symmetric (data transfer) encryption. Certificates and Certificate Authorities establish trust.`,
  ],
  '🏛️ history': [
    `The French Revolution (1789-1799) was a period of radical political and societal change in France. Key causes: financial crisis, social inequality under the Estates system, Enlightenment ideas. Major events: Storming of the Bastille (July 14, 1789), Declaration of the Rights of Man, Reign of Terror under Robespierre, rise of Napoleon Bonaparte. The revolution abolished feudalism and the monarchy, established a republic, and introduced principles of citizenship and rights. It influenced democratic movements worldwide and led to the Napoleonic Wars.`,
    `The Industrial Revolution (1760-1840) transformed Britain from an agrarian society to an industrial powerhouse. Key innovations: spinning jenny, water frame, steam engine (James Watt), power loom. Factory systems replaced cottage industries, driving urbanization. Coal and iron became critical resources. Transportation revolutionized by railways and canals. Social impacts included child labor, poor working conditions, and the rise of a new middle class. The Luddite movement opposed mechanization. Trade unions emerged to protect workers' rights. The revolution spread to Europe, America, and eventually the world.`,
    `The Cold War (1947-1991) was a geopolitical rivalry between the United States and Soviet Union. It began after WWII with ideological conflict: capitalism vs communism. Key events: Berlin Blockade (1948), Korean War (1950-53), Cuban Missile Crisis (1962), Vietnam War, Space Race. NATO and the Warsaw Pact divided Europe. The arms race produced massive nuclear arsenals and the doctrine of Mutually Assured Destruction (MAD). Proxy wars were fought across Asia, Africa, and Latin America. Détente in the 1970s eased tensions temporarily. The fall of the Berlin Wall (1989) and Soviet dissolution (1991) ended the conflict.`,
    `Ancient Rome evolved from a kingdom (753 BC) to a republic (509 BC) to an empire (27 BC). The Republic featured a Senate, consuls, and popular assemblies. Expansion through military conquest brought wealth but also social tensions — the Gracchi reforms, Marius' military reforms, and civil wars between Sulla, Pompey, and Caesar. Augustus established the Principate after defeating Antony. The Pax Romana (27 BC-180 AD) brought stability and prosperity. Roman law, engineering (aqueducts, roads, Colosseum), and Latin language shaped Western civilization. The empire split in 285 AD and the Western half fell in 476 AD.`,
    `World War I (1914-1918) was triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary. Underlying causes: militarism, alliances, imperialism, and nationalism (MAIN). The war introduced trench warfare on the Western Front, chemical weapons, tanks, and aircraft. Major battles: Somme, Verdun, Gallipoli, Marne. The Eastern Front saw movement but massive casualties. The United States entered in 1917, tipping the balance. The Treaty of Versailles imposed harsh reparations on Germany, redrew borders, and created the League of Nations. The war killed approximately 17 million people and set the stage for WWII.`,
    `The Renaissance (14th-17th century) was a cultural rebirth originating in Italian city-states like Florence, Venice, and Rome. Wealthy patrons like the Medici funded art and scholarship. Key figures: Leonardo da Vinci (art, science), Michelangelo (Sistine Chapel, David), Raphael (School of Athens), Machiavelli (The Prince). Humanism emphasized individual potential and classical Greek-Roman learning. The printing press (Gutenberg, 1440) democratized knowledge. Scientific advances challenged medieval worldviews — Copernicus proposed heliocentrism. The Renaissance spread north, influencing Erasmus, Shakespeare, and Dürer. It laid foundations for the Scientific Revolution and Enlightenment.`,
    `Ancient Greece (800-146 BC) was the cradle of Western civilization. Athens developed direct democracy under Cleisthenes and Pericles. Sparta was a militaristic society with a dual kingship. The Persian Wars (490-479 BC) united Greek city-states — key battles at Marathon, Thermopylae, and Salamis. The Peloponnesian War (431-404 BC) between Athens and Sparta weakened Greece. Alexander the Great spread Hellenistic culture across Persia, Egypt, and India. Greek contributions include philosophy (Socrates, Plato, Aristotle), drama (Sophocles, Euripides), mathematics (Euclid, Pythagoras), medicine (Hippocrates), and the Olympic Games.`,
    `The Age of Exploration (15th-17th century) was driven by European desire for trade routes, wealth, and religious expansion. Portugal led under Prince Henry the Navigator — Dias rounded the Cape of Good Hope (1488), da Gama reached India (1498). Spain funded Columbus (1492), who reached the Americas. Magellan's expedition (1519-1522) first circumnavigated the globe. The Columbian Exchange transferred crops, animals, diseases, and ideas between hemispheres. European colonization devastated indigenous populations through disease and conquest. The Treaty of Tordesillas (1494) divided the New World between Spain and Portugal.`,
    `The American Civil War (1861-1865) was fought between the Union (North) and Confederacy (South) over slavery, states' rights, and economic differences. Lincoln's election in 1860 triggered Southern secession. Key battles: Fort Sumter, Bull Run, Gettysburg, Antietam, Vicksburg, Sherman's March. The Emancipation Proclamation (1863) declared slaves in Confederate states free. The 13th Amendment abolished slavery. Approximately 620,000 soldiers died — the deadliest American conflict. Reconstruction (1865-1877) attempted to rebuild the South and integrate freed slaves, but faced resistance through Black Codes, the KKK, and Jim Crow laws.`,
    `The Byzantine Empire (330-1453 AD) was the eastern continuation of the Roman Empire, centered on Constantinople. Emperor Justinian I (527-565) reconquered parts of the west and codified Roman law (Corpus Juris Civilis). The empire preserved Greek and Roman knowledge through the medieval period. Eastern Orthodox Christianity became the state religion, leading to the Great Schism of 1054 with Roman Catholicism. Byzantine art and architecture (Hagia Sophia, mosaics, icons) influenced Eastern European culture. The empire faced threats from Persians, Arabs, Seljuk Turks, and Crusaders. Constantinople fell to the Ottoman Turks in 1453, ending the empire.`,
  ],
  '⚛️ physics': [
    `Newton's three laws of motion form the foundation of classical mechanics. First law (inertia): an object at rest stays at rest, an object in motion stays in motion unless acted on by a net external force. Second law: F = ma — force equals mass times acceleration. Third law: for every action there is an equal and opposite reaction. Weight is the gravitational force on an object (W = mg). Friction opposes motion and depends on the normal force and coefficient of friction. Free body diagrams help analyze forces. These laws break down at very high speeds (relativity) or very small scales (quantum mechanics).`,
    `Thermodynamics governs energy transfer and transformation. The zeroth law establishes thermal equilibrium and temperature. First law: energy is conserved — ΔU = Q - W (internal energy change equals heat added minus work done). Second law: entropy of an isolated system never decreases; heat flows from hot to cold spontaneously. Third law: entropy approaches zero as temperature approaches absolute zero. Carnot efficiency sets the maximum efficiency of heat engines: η = 1 - Tc/Th. Entropy measures disorder. Reversible processes are idealizations; real processes are irreversible and increase total entropy.`,
    `Electromagnetic waves are oscillating electric and magnetic fields that propagate through space at the speed of light (c ≈ 3×10⁸ m/s). Maxwell's equations unify electricity, magnetism, and optics. The electromagnetic spectrum ranges from radio waves (long wavelength) to gamma rays (short wavelength). Visible light occupies a narrow band (400-700 nm). Wave properties include reflection, refraction (Snell's law), diffraction, and interference. Photons are the quantum of EM radiation with energy E = hf. Polarization shows the transverse nature of EM waves. Applications span communications, medicine, astronomy, and technology.`,
    `Special relativity, proposed by Einstein in 1905, rests on two postulates: the laws of physics are the same in all inertial frames, and the speed of light is constant regardless of the observer's motion. Consequences include time dilation (moving clocks tick slower), length contraction (moving objects shorten), and mass-energy equivalence (E = mc²). Simultaneity is relative — events simultaneous in one frame may not be in another. The Lorentz factor γ = 1/√(1-v²/c²) quantifies these effects. Nothing with mass can reach the speed of light. GPS satellites must account for relativistic time corrections.`,
    `Quantum mechanics describes physics at atomic and subatomic scales. Wave-particle duality means particles exhibit both wave and particle properties. The Heisenberg uncertainty principle states you cannot simultaneously know exact position and momentum — ΔxΔp ≥ ℏ/2. Schrödinger's equation describes how quantum states evolve over time. The wave function ψ gives probability amplitudes — |ψ|² is the probability density. Quantum superposition allows particles to exist in multiple states simultaneously until measured. Entanglement links particles so measuring one instantly affects the other regardless of distance. Applications include lasers, semiconductors, and quantum computing.`,
    `Waves transfer energy without transferring matter. Transverse waves oscillate perpendicular to propagation (light, water surface); longitudinal waves oscillate parallel (sound). Key properties: wavelength (λ), frequency (f), amplitude, period (T = 1/f), and speed (v = fλ). Superposition allows waves to combine — constructive interference increases amplitude, destructive interference cancels. Standing waves form in confined spaces with nodes and antinodes. The Doppler effect shifts frequency when source or observer moves — approaching sources have higher pitch, receding sources have lower pitch. Resonance occurs when driving frequency matches natural frequency.`,
    `Electric circuits involve the flow of charge through conductors. Current (I) is charge flow per time, measured in amperes. Voltage (V) is the potential difference that drives current. Resistance (R) opposes current flow — Ohm's law: V = IR. Power: P = IV = I²R = V²/R. Series circuits have the same current through all components; total resistance adds. Parallel circuits have the same voltage across branches; reciprocal resistances add. Kirchhoff's laws: junction rule (currents in = currents out) and loop rule (voltage gains = voltage drops around any loop). Capacitors store charge; inductors store energy in magnetic fields.`,
    `Nuclear physics studies atomic nuclei and their interactions. The strong nuclear force binds protons and neutrons, overcoming electromagnetic repulsion at short range. Binding energy per nucleon peaks at iron-56 — lighter nuclei release energy through fusion, heavier ones through fission. Radioactive decay types: alpha (helium nucleus emitted), beta (neutron converts to proton or vice versa), gamma (high-energy photon). Half-life is the time for half a sample to decay. Nuclear fission powers reactors — uranium-235 absorbs a neutron and splits. Nuclear fusion powers stars — hydrogen fuses into helium at extreme temperatures and pressures.`,
    `Fluid mechanics studies liquids and gases at rest and in motion. Pressure = Force/Area, measured in Pascals. Pascal's principle: pressure applied to a confined fluid transmits equally in all directions (hydraulic systems). Archimedes' principle: buoyant force equals the weight of displaced fluid — objects float when buoyancy exceeds weight. Bernoulli's equation relates pressure, velocity, and height in flowing fluids — faster flow means lower pressure (airplane lift, venturi effect). Viscosity measures fluid resistance to flow. Reynolds number predicts laminar vs turbulent flow. The continuity equation (A₁v₁ = A₂v₂) ensures mass conservation in flowing fluids.`,
    `Optics studies the behavior of light. Reflection follows the law: angle of incidence equals angle of reflection. Refraction bends light at interfaces — Snell's law: n₁sinθ₁ = n₂sinθ₂. Total internal reflection occurs when light hits a less dense medium beyond the critical angle (fiber optics). Lenses form images — converging (convex) lenses focus light, diverging (concave) lenses spread it. The thin lens equation: 1/f = 1/do + 1/di. Diffraction bends light around obstacles and through slits. Young's double-slit experiment demonstrated wave nature of light. Polarization filters oscillations to one plane. Optical instruments: microscopes, telescopes, cameras.`,
  ],
  '📐 mathematics': [
    `Calculus studies rates of change (derivatives) and accumulation (integrals). The derivative f'(x) gives the slope of f(x) at any point. Basic rules: power rule (d/dx xⁿ = nxⁿ⁻¹), product rule, quotient rule, chain rule. The integral ∫f(x)dx reverses differentiation. The Fundamental Theorem of Calculus links derivatives and integrals. Definite integrals compute areas under curves. Applications include velocity/acceleration, optimization problems, and modeling growth. L'Hôpital's rule resolves indeterminate forms. Taylor series approximate functions as infinite polynomials. Multivariable calculus extends to partial derivatives and multiple integrals.`,
    `Linear algebra studies vectors, matrices, and linear transformations. A vector space is a set with addition and scalar multiplication satisfying axioms. Matrices represent linear maps; multiplication corresponds to composition. The determinant measures scaling factor — if zero, the matrix is singular (non-invertible). Eigenvalues λ satisfy Av = λv; eigenvectors define invariant directions. Row reduction (Gaussian elimination) solves systems of linear equations. Rank determines the dimension of the column space. The spectral theorem states symmetric matrices have orthogonal eigenvectors. Applications: computer graphics, machine learning, quantum mechanics, network analysis.`,
    `Probability theory quantifies uncertainty. The probability of event A is P(A) ∈ [0,1]. Complementary events: P(A') = 1 - P(A). For independent events: P(A∩B) = P(A)·P(B). Bayes' theorem: P(A|B) = P(B|A)·P(A)/P(B). Random variables map outcomes to numbers. Expected value E[X] = Σ xᵢP(xᵢ). Variance measures spread: Var(X) = E[(X-μ)²]. The normal distribution is bell-shaped with 68-95-99.7 rule. The central limit theorem states sample means approach normal distribution regardless of population shape. Law of large numbers: sample averages converge to expected value.`,
    `Number theory studies properties of integers. Prime numbers have exactly two divisors (1 and themselves). The Fundamental Theorem of Arithmetic states every integer > 1 has a unique prime factorization. Euclid proved infinitely many primes exist. The Euclidean algorithm finds the GCD of two numbers efficiently. Modular arithmetic works with remainders — a ≡ b (mod n) means n divides (a-b). Fermat's Little Theorem: aᵖ⁻¹ ≡ 1 (mod p) for prime p. The Chinese Remainder Theorem solves systems of congruences. RSA encryption relies on the difficulty of factoring large semiprimes. The Riemann Hypothesis about prime distribution remains unproven.`,
    `Graph theory studies networks of vertices and edges. A graph G = (V, E) consists of vertices and edges connecting them. Graphs can be directed or undirected, weighted or unweighted. Degree of a vertex is the number of edges incident to it. A path is a sequence of edges connecting vertices; a cycle is a closed path. Connected graphs have paths between all vertex pairs. Trees are connected acyclic graphs with n-1 edges. Euler paths visit every edge exactly once; Hamiltonian paths visit every vertex exactly once. Planar graphs can be drawn without edge crossings — Euler's formula: V - E + F = 2. Graph coloring assigns colors so adjacent vertices differ.`,
    `Differential equations describe how quantities change. An ODE (ordinary differential equation) involves functions of one variable. Order is the highest derivative present. First-order separable: dy/dx = f(x)g(y) — separate and integrate. Linear first-order: dy/dx + P(x)y = Q(x) — use integrating factor e^∫P dx. Second-order linear with constant coefficients: ay'' + by' + cy = 0 — solve characteristic equation ar² + br + c = 0. Solutions depend on discriminant: real distinct roots, repeated roots, or complex conjugate roots. Applications: population models, spring-mass systems, electrical circuits, heat conduction.`,
    `Set theory is the foundation of modern mathematics. A set is a collection of distinct objects. Operations: union (A∪B), intersection (A∩B), complement (Aᶜ), difference (A\B). De Morgan's laws: (A∪B)ᶜ = Aᶜ∩Bᶜ and (A∩B)ᶜ = Aᶜ∪Bᶜ. Subsets: A⊆B if every element of A is in B. Cardinality |A| counts elements. For finite sets: |A∪B| = |A| + |B| - |A∩B|. Power set P(A) has 2^|A| elements. Cartesian product A×B = {(a,b) | a∈A, b∈B}. Functions map elements between sets — injective (one-to-one), surjective (onto), bijective (both). Cantor proved real numbers are uncountably infinite while rationals are countable.`,
    `Complex analysis extends calculus to complex numbers z = a + bi, where i² = -1. The complex plane has real and imaginary axes. Polar form: z = r·e^(iθ) where r = |z| and θ = arg(z). Euler's formula: e^(iθ) = cos(θ) + i·sin(θ). Analytic functions are differentiable everywhere in their domain and satisfy the Cauchy-Riemann equations. Cauchy's integral theorem states that integrals of analytic functions over closed curves equal zero. The residue theorem evaluates integrals using singularities. Conformal mappings preserve angles. Applications include fluid dynamics, electrical engineering, quantum mechanics, and number theory.`,
    `Statistics uses data to make inferences about populations. Descriptive statistics summarize data: mean (average), median (middle value), mode (most frequent), standard deviation (spread). A sample is a subset of a population. Hypothesis testing evaluates claims: null hypothesis (H₀) vs alternative (H₁). P-value is the probability of observing results as extreme as the data, assuming H₀ is true. Significance level α (typically 0.05) sets the rejection threshold. Type I error: rejecting true H₀ (false positive). Type II error: failing to reject false H₀ (false negative). Confidence intervals estimate parameters with a given confidence level.`,
    `Topology studies properties preserved under continuous deformations (stretching, bending — not tearing or gluing). A topological space generalizes the notion of geometric shape. Homeomorphisms are continuous bijections with continuous inverses — a donut and coffee cup are topologically equivalent (both genus 1). Key concepts: open and closed sets, continuity, compactness, connectedness. The Euler characteristic χ = V - E + F classifies surfaces. The fundamental group captures loops in a space. The Möbius strip is a non-orientable surface with one side. The Brouwer fixed-point theorem guarantees fixed points for continuous maps on closed balls.`,
  ],
  '🧪 chemistry': [
    `Chemical bonding determines molecular structure and properties. Ionic bonds form between metals and non-metals through electron transfer — Na⁺Cl⁻. Covalent bonds share electrons — H₂O has two O-H bonds. Metallic bonds create a sea of delocalized electrons explaining conductivity. VSEPR theory predicts molecular geometry from electron pair repulsion. Electronegativity differences determine bond polarity. Hybridization (sp, sp², sp³) explains bond angles — methane is tetrahedral (109.5°), ethylene is trigonal planar (120°). Intermolecular forces (London dispersion, dipole-dipole, hydrogen bonding) affect boiling points and solubility.`,
    `Organic chemistry studies carbon-containing compounds. Carbon forms four bonds and chains/rings of variable length. Functional groups determine reactivity: -OH (alcohol), -COOH (carboxylic acid), -NH₂ (amine), C=O (carbonyl). Hydrocarbons: alkanes (single bonds), alkenes (double bonds), alkynes (triple bonds). Isomers have the same formula but different structures. Stereoisomers include enantiomers (mirror images) and diastereomers. Reaction types: substitution, addition, elimination, condensation. Polymers form through addition or condensation polymerization. Organic molecules are the basis of biochemistry — proteins, carbohydrates, lipids, nucleic acids.`,
    `Chemical equilibrium occurs when forward and reverse reaction rates are equal. The equilibrium constant K = [products]/[reactants] (each raised to stoichiometric coefficients). Large K favors products; small K favors reactants. Le Chatelier's principle: if a system at equilibrium is disturbed, it shifts to counteract the change. Increasing concentration of reactants shifts equilibrium toward products. Increasing temperature shifts equilibrium in the endothermic direction. Pressure changes affect gaseous equilibria — increasing pressure favors the side with fewer gas moles. Catalysts speed up both directions equally without changing K.`,
    `Acids and bases are fundamental to chemistry. Arrhenius: acids produce H⁺, bases produce OH⁻ in water. Brønsted-Lowry: acids donate protons, bases accept protons. Lewis: acids accept electron pairs, bases donate electron pairs. pH = -log[H⁺]; pH 7 is neutral, below 7 is acidic, above 7 is basic. Strong acids/bases dissociate completely (HCl, NaOH). Weak acids/bases partially dissociate (CH₃COOH, NH₃). Buffer solutions resist pH changes — made of weak acid + conjugate base. Titration determines concentration by neutralization. The Henderson-Hasselbalch equation: pH = pKa + log([A⁻]/[HA]).`,
    `Electrochemistry studies the relationship between electrical energy and chemical reactions. Oxidation loses electrons; reduction gains electrons (OIL RIG). Galvanic cells convert chemical energy to electrical energy — spontaneous reactions with positive cell potential (E°cell > 0). Electrolytic cells use electrical energy to drive non-spontaneous reactions. Standard reduction potentials rank species by tendency to gain electrons. The Nernst equation adjusts cell potential for non-standard conditions. Faraday's laws relate charge passed to mass of substance deposited. Applications include batteries, fuel cells, electroplating, and corrosion prevention.`,
    `Thermochemistry studies heat changes in chemical reactions. Enthalpy (H) measures heat content at constant pressure. Exothermic reactions release heat (ΔH < 0); endothermic reactions absorb heat (ΔH > 0). Hess's law: total enthalpy change is independent of the pathway. Standard enthalpy of formation (ΔHf°) is the enthalpy change when one mole of compound forms from elements in standard states. Bond energies estimate ΔH: energy to break bonds minus energy to form bonds. Calorimetry measures heat changes: q = mcΔT. Gibbs free energy (ΔG = ΔH - TΔS) determines spontaneity — negative ΔG means spontaneous.`,
    `The periodic table organizes elements by atomic number and electron configuration. Periods (rows) represent energy levels; groups (columns) share valence electron counts and properties. Alkali metals (Group 1) are highly reactive with one valence electron. Noble gases (Group 18) have full outer shells and are inert. Transition metals (Groups 3-12) have partially filled d orbitals and variable oxidation states. Trends: atomic radius decreases left-to-right (more protons pull electrons closer), increases top-to-bottom. Ionization energy and electronegativity increase left-to-right. Metallic character increases going left and down.`,
    `Chemical kinetics studies reaction rates and mechanisms. Rate = change in concentration per unit time. Rate laws express rate as a function of reactant concentrations: Rate = k[A]ᵐ[B]ⁿ where k is the rate constant and m, n are orders. Zero-order: rate independent of concentration. First-order: rate proportional to concentration (half-life = ln2/k). Second-order: rate proportional to concentration squared. Activation energy (Ea) is the minimum energy for reaction — Arrhenius equation: k = Ae^(-Ea/RT). Catalysts lower Ea without being consumed. Reaction mechanisms propose step-by-step pathways; the slowest step determines overall rate.`,
    `Atomic structure describes the arrangement of subatomic particles. The nucleus contains protons (positive) and neutrons (neutral); electrons (negative) orbit in shells. Atomic number = protons; mass number = protons + neutrons. Isotopes have the same atomic number but different neutron counts. The quantum mechanical model describes electron probability clouds (orbitals). Quantum numbers: n (principal/energy level), l (angular momentum/shape), ml (magnetic/orientation), ms (spin). The Aufbau principle fills lowest energy orbitals first. Pauli exclusion: no two electrons share all four quantum numbers. Hund's rule: electrons fill degenerate orbitals singly first.`,
    `Stoichiometry is the quantitative study of chemical reactions. Balanced equations show mole ratios of reactants and products. The mole (6.022 × 10²³ particles) bridges atomic and macroscopic scales. Molar mass (g/mol) converts between grams and moles. Limiting reagent is the reactant that runs out first, determining maximum product yield. Theoretical yield is the maximum possible product; actual yield is what's obtained. Percent yield = (actual/theoretical) × 100%. Solution concentration: molarity (M) = moles solute / liters solution. Dilution formula: M₁V₁ = M₂V₂. Gas stoichiometry uses the ideal gas law: PV = nRT at STP (0°C, 1 atm).`,
  ],
}

const labels = Object.keys(samples)

export function SampleNotes({ onSelect, compact }: SampleNotesProps) {
  const indexRef = useRef<Record<string, number>>({})

  const handleClick = useCallback(
    (label: string) => {
      const pool = samples[label]
      const current = indexRef.current[label] ?? 0
      onSelect(pool[current % pool.length])
      indexRef.current[label] = current + 1
    },
    [onSelect],
  )

  if (compact) {
    return (
      <div className="flex items-center gap-1.5 flex-wrap">
        <span className="text-[10px] text-surface-500 uppercase tracking-wider font-bold font-display shrink-0">Samples</span>
        {labels.map((label) => {
          const [emoji, ...rest] = label.split(' ')
          const name = rest.join(' ')
          return (
            <button
              key={label}
              onClick={() => handleClick(label)}
              className="flex items-center gap-1 px-2 py-1 rounded-lg text-[11px] text-surface-500 border border-surface-300 hover:border-surface-400 hover:text-surface-700 transition-all font-modern lowercase"
            >
              <span className="text-xs">{emoji}</span>
              {name}
            </button>
          )
        })}
      </div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 0.5 }}
    >
      <p className="text-[11px] font-modern text-surface-500 uppercase tracking-[0.12em] mb-3">
        or try with sample notes
      </p>
      <div className="flex flex-wrap gap-2">
        {labels.map((label) => {
          const [emoji, ...rest] = label.split(' ')
          const name = rest.join(' ')
          return (
            <button
              key={label}
              onClick={() => handleClick(label)}
              className="flex items-center gap-2 px-4 py-2.5 border border-surface-300 text-[13px] font-modern tracking-[0.04em] lowercase text-surface-700 hover:bg-surface-100 hover:text-surface-900 transition-all duration-200"
            >
              <span className="text-base">{emoji}</span>
              {name}
            </button>
          )
        })}
      </div>
    </motion.div>
  )
}
